version: '3'

services:
  postgres_datastore:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - database_data:/var/lib/postgresql/data

  mongo_datastore:
    image: 'mongo:latest'
    ports:
      - '27100:27017'
    env_file:
      - .env

  mongo_seed:
    build: seed-data
    depends_on:
      - mongo_datastore
    env_file:
      - .env

  test:
    build:
      context: crates/api
      dockerfile: Dockerfile-test
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - postgres_datastore
    env_file:
      - .env

volumes:
  database_data:
    driver: local
