version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - database_data:/var/lib/postgresql/data

  test:
    build:
      context: crates/api
      dockerfile: Dockerfile-test
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  database_data:
    driver: local
