version: '3'

services:
  mongo_datastore:
    image: 'mongo:latest'
    ports:
      - '27100:27017'
    env_file:
      - .env

  mongo_seed:
    build: seed-data
    depends_on:
      - mongo_datastore
    env_file:
      - .env

  test:
    build: crates/api/test.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - mongo_datastore
      - mongo_seed
    env_file:
      - .env
    environment:
      - ROCKET_DATABASES={mongo_datastore={url="mongodb://mongo_datastore:27017/playground"}}
