version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: ./db/Dockerfile.postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - PGDATA=/tmp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=develop
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init/01-CreateFiler.sql:/docker-entrypoint-initdb.d/01-CreateFiler.sql

  test:
    build:
      context: crates/api
      dockerfile: Dockerfile-test
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
    driver: local
