version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: ./db/Dockerfile.postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init/01-CreateFiler.sql:/docker-entrypoint-initdb.d/01-CreateFiler.sql

volumes:
  pgdata:
    driver: local
