version: '3'

services:
  mongo_datastore:
    image: 'mongo:latest'
    ports:
      - '27100:27017'
    env_file:
      - .env

  mongo_seed:
    build: seed-data
    links:
      - mongo_datastore
    env_file:
      - .env
