version: '3'

services:
  mongo_datastore:
    image: 'mongo:latest'
    ports:
      - '27100:27017'
  api:
    build: crates/api
    ports:
      - 8000:8000
    volumes:
      - ./crates/api:/usr/src/app
    depends_on:
      - mongo_datastore
    environment:
      # For Rocket's purposes we have to store the connection
      # string in crates/api/Rocket.toml. These DB_... values
      # are not used at the moment.
      - DB_NAME:playground
      - DB_PORT:27017
      - DB_HOST:mongo_datastore
      - PORT:8000
      - ROCKET_ENV:development
    command: "cargo watch -x run"
