version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  test:
    build:
      context: crates/server
      dockerfile: Dockerfile-test
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
    driver: local
