[package]
name = "bb"
version = "0.1.14"
authors = ["'Marty'"]
edition = "2018"
publish = false

[dependencies]
clap = "2.33"
colored = "1.8.0"
dirs = "1.0"
failure = "0.1.5"
lazy_static = "1.3.0"
regex = "1.1.6"
structopt = "0.2"
