[package]
name = "aws"
version = "0.1.0"
authors = ["Marty Jones <murtin.jones@gmail.com>"]
edition = "2018"

[dependencies]
rusoto_core = "0.40"
rusoto_s3 = "0.40"
rusoto_credential = "0.40.0"
futures = "0.1.28"
