version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
#      - restore_cache:
#          keys:
#            - v1-cargo-cache-{{ arch }}-{{ .Branch }} # Cache for the branch that you're on
#            - v1-cargo-cache-{{ arch }}- # If that doesn't exist, use the default cache across all branches
      - run:
          name: Install Rust nightly
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
            rustup default nightly
      - run:
          name: Run Docker-Compose
          command: make
      - run:
          name: Tests
          command: cargo test --all
      - save_cache:
          key: v1-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
