version: 2
jobs:
  test:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: Tests
          command: cargo test --all

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
