version: 2
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.3
jobs:
  test_and_build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-cargo-cache-{{ arch }}-{{ .Branch }} # Cache for the branch that you're on
            - v3-cargo-cache-{{ arch }}- # If that doesn't exist, use the default cache across all branches
#      - run:
#          name: Run tests
#          command: |
#            make test
      - run:
          name: Build image
          command: make release-build
      - run:
          name: Tag latest
          command: |
            make release-tag-latest
      - save_cache:
          key: v3-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo


workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test_and_build
      - aws-ecr/build_and_push_image:
          requires:
            - test_and_build
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
