version: 2
jobs:
  test:
    machine: true
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ .Branch }} # Cache for the branch that you're on
            - v1-cargo-cache-{{ arch }}- # If that doesn't exist, use the default cache across all branches
            -
      - run:
          name: Tests
          command: make test
      - save_cache:
          key: v1-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
