version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-cargo-cache-{{ arch }}-{{ .Branch }} # Cache for the branch that you're on
            - v3-cargo-cache-{{ arch }}- # If that doesn't exist, use the default cache across all branches
      - run:
          name: Run tests
          command: |
            make test
      - run:
          name: Build image
          command: make release-build
      - save_cache:
          key: v3-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
