version: 2.1
jobs:
  install-birb-cli:
    docker:
      - image: rust:latest
    working_directory: ~/birb/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - cli-release-v2-{{ .Branch }}
            - cli-release-v2-

      - run: cargo install --path ./crates/birb-cli --force
      - save_cache:
          key: cli-release-v2-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
            - $HOME/.cargo/registry
      - run:
          name: Make birb-cli binary available to other jobs
          command: |
            mkdir bb-cli-workspace
            mv /usr/local/cargo/bin/bb bb-cli-workspace/
      - persist_to_workspace:
          root: bb-cli-workspace
          paths:
            - bb

  check:
    docker:
      - image: rustlang/rust:nightly
    working_directory: ~/birb/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-check-cache-{{ .Branch }}-{{ checksum "Cargo.lock" }} # Cache for the branch that you're on with this lockfile
            - v1-check-cache-{{ checksum "Cargo.lock" }} # If that doesn't exist, use the default cache across all branches with this lockfile
      - run: cargo check --all
      - save_cache:
          key: v1-check-cache-{{ .Branch }}-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - /usr/local/cargo
            - $HOME/.cargo/registry


  test-edgar:
    docker:
      - image: rustlang/rust:nightly
    working_directory: ~/birb/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-edgar-cache-{{ .Branch }}-{{ checksum "Cargo.lock" }} # Cache for the branch that you're on with this lockfile
            - v1-edgar-cache-{{ checksum "Cargo.lock" }} # If that doesn't exist, use the default cache across all branches with this lockfile
      - attach_workspace:
          at: bb-cli-workspace

      - run:
          name: Test edgar worker
          command: cargo test -p edgar-worker

  test-server:
    docker:
      - image: rustlang/rust:nightly
    working_directory: ~/birb/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-server-cache-{{ .Branch }}-{{ checksum "Cargo.lock" }} # Cache for the branch that you're on with this lockfile
            - v1-server-cache-{{ checksum "Cargo.lock" }} # If that doesn't exist, use the default cache across all branches with this lockfile
      - attach_workspace:
          at: bb-cli-workspace
      - run:
          name: Test edgar worker
          command: cargo test -p edgar-worker

  build-deploy-edgar:
    machine: true
    working_directory: ~/birb/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-edgar-cache-{{ .Branch }}-{{ checksum "Cargo.lock" }} # Cache for the branch that you're on with this lockfile
            - v1-edgar-cache-{{ checksum "Cargo.lock" }} # If that doesn't exist, use the default cache across all branches with this lockfile
      - attach_workspace:
          at: bb-cli-workspace
      - run:
          name: Get birb-cli binary
          command: mv bb-cli-workspace/bb ./
      - run:
          name: Build edgar worker binary
          command: scripts/build_binary.sh edgar-worker
      - run:
          name: Upgrade AWS CLI Latest Version
          command: pip install --upgrade awscli
      - run:
          name: Deploy edgar worker binary
          command: scripts/build_push_edgar_worker.sh
      - save_cache:
          key: v1-edgar-cache-{{ .Branch }}-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - /usr/local/cargo
            - $HOME/.cargo/registry

  build-server:
    docker:
      - image: clux/muslrust:nightly
    working_directory: /volume
    steps:
      - checkout
      - run: echo 'export CACHE_VERSION="12' >> $BASH_ENV
      - restore_cache:
          keys:
            - cargo.registry.release-{{ .Environment.CACHE_VERSION }}
      - restore_cache:
          keys:
            - target.release-{{ .Environment.CACHE_VERSION }}
      - run: cargo build -p server --release
      - save_cache:
          key: target.release-{{ .Environment.CACHE_VERSION }}
          paths:
            - target
      - save_cache:
          key: cargo.registry.release-{{ .Environment.CACHE_VERSION }}
          paths:
            - /root/.cargo
      - persist_to_workspace:
          root: target/x86_64-unknown-linux-musl/release/
          paths:
            - .

  deploy-server:
    machine: true
    working_directory: ~/birb/app
    steps:
      - attach_workspace:
          at: target/x86_64-unknown-linux-musl/release/
      - run:
          name: List the folder contents
          command: ls
      - run:
          name: List the folder contents
          command: ls target/x86_64-unknown-linux-musl/release/

  build-deploy-server:
    machine: true
    working_directory: ~/birb/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-server-cache-{{ .Branch }}-{{ checksum "Cargo.lock" }} # Cache for the branch that you're on with this lockfile
            - v1-server-cache-{{ checksum "Cargo.lock" }} # If that doesn't exist, use the default cache across all branches with this lockfile
      - attach_workspace:
          at: bb-cli-workspace
      - run:
          name: Get birb-cli binary
          command: mv bb-cli-workspace/bb ./
      - run:
          name: Build edgar worker binary
          command: scripts/build_binary.sh server
      - run:
          name: Upgrade AWS CLI Latest Version
          command: pip install --upgrade awscli
      - run:
          name: Deploy server binary
          command: scripts/build_push_server.sh
      - save_cache:
          key: v1-server-cache-{{ .Branch }}-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - /usr/local/cargo
            - $HOME/.cargo/registry

workflows:
  version: 2
  edgar:
    jobs:
#      - install-birb-cli
#      - check
#      - test-edgar:
#          requires:
#            - install-birb-cli
#            - check
#      - build-deploy-edgar:
#          requires:
#            - test-edgar
#      - test-server:
#          requires:
#            - install-birb-cli
#            - check
#      - build-deploy-server:
#          requires:
#            - test-server
      - build-server
      - deploy-server:
          requires:
            - build-server
