version: 2.1
jobs:
  build_and_deploy:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v7-cargo-cache-{{ arch }}-{{ .Branch }} # Cache for the branch that you're on
            - v7-cargo-cache-{{ arch }}- # If that doesn't exist, use the default cache across all branches
      - run:
          name: Upgrade AWS CLI Latest Version
          command: pip install --upgrade awscli
      - run:
          name: Run Tests
          command: make test
      - run:
          name: Build Binary
          command: make build-api-release
      - run:
          name: Copy Binary and Production Dockerfile to "./out"
          command: make copy-artifacts
      - run:
          name: Build Image and Push to ECS
          command: ./scripts/build_and_push.sh
      - save_cache:
          key: v8-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
            - /root/.cargo

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy
