version: 2.1

jobs:
  build-bb:
    docker:
      - image: rust:latest
    working_directory: ~/birb/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - cli-release-v1-{{ arch }}-{{ .Branch }}
            - cli-release-v1-{{ arch }}-

      - run: cargo install --path ./crates/birb-cli --force

      # Save release cache
      - save_cache:
          key: cli-release-v1-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo

      - run: mkdir bb-cli-workspace && mv /usr/local/cargo/bin/bb bb-cli-workspace/

      - persist_to_workspace:
          root: bb-cli-workspace
          paths:
            - bb

  use-bb:
    machine: true
    working_directory: ~/birb/app
    steps:
      - attach_workspace:
          at: bb-cli-workspace

      - run: mv bb-cli-workspace/bb /usr/local/cargo/bin/

      - run: ./bb --version


  build_test_deploy:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v8-cargo-cache-{{ arch }}-{{ .Branch }} # Cache for the branch that you're on
            - v8-cargo-cache-{{ arch }}- # If that doesn't exist, use the default cache across all branches
      - run:
          name: Install Rust
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
            rustup toolchain install nightly
            rustup default nightly
      - run:
          name: Install birb cli
          command: |
            source $HOME/.cargo/env
            cargo install --path crates/birb-cli --force
      - run:
          name: Run Tests
          command: bb test all
      - run:
          name: Upgrade AWS CLI Latest Version
          command: pip install --upgrade awscli
      - run:
          name: Build API Binary
          command: bb build api
      - run:
          name: Build Image and Push to ECS
          command: bb push api
      - save_cache:
          key: v8-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
            - /root/.cargo

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-bb
      - use-bb
        requires:
          - build-bb
