version: 2
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.3
jobs:
  test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-cargo-cache-{{ arch }}-{{ .Branch }} # Cache for the branch that you're on
            - v3-cargo-cache-{{ arch }}- # If that doesn't exist, use the default cache across all branches
#      - run:
#          name: Run tests
#          command: |
#            make test
      - run:
          name: Build image
          command: make release-build
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: "$AWS_ACCESS_KEY_ID"
          aws-region: "$AWS_DEFAULT_REGION"
      - run:
          name: Tag and push to ECR
          command: |
            make release-tag-latest
            make ecr-login
            make ecr-push
      - save_cache:
          key: v3-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
