version: 2.1

jobs:
  install-birb-cli:
    docker:
      - image: rust:latest
    working_directory: ~/birb/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - cli-release-v1-{{ arch }}-{{ .Branch }}
            - cli-release-v1-{{ arch }}-

      - run: cargo install --path ./crates/birb-cli --force
      - save_cache:
          key: cli-release-v1-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
      - run:
          name: Make birb-cli binary available to other jobs
          command: |
            mkdir bb-cli-workspace
            mv /usr/local/cargo/bin/bb bb-cli-workspace/
      - persist_to_workspace:
          root: bb-cli-workspace
          paths:
            - bb

  test-edgar:
    docker:
      - image: rustlang/rust:nightly
    working_directory: ~/birb/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v9-cargo-cache-{{ arch }}-{{ .Branch }} # Cache for the branch that you're on
            - v9-cargo-cache-{{ arch }}- # If that doesn't exist, use the default cache across all branches
      - attach_workspace:
          at: bb-cli-workspace

      - run:
          name: Test edgar worker
          command: cargo test -p edgar-worker

  build-edgar:
    machine: true
    working_directory: ~/birb/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v9-cargo-cache-{{ arch }}-{{ .Branch }} # Cache for the branch that you're on
            - v9-cargo-cache-{{ arch }}- # If that doesn't exist, use the default cache across all branches
      - attach_workspace:
          at: bb-cli-workspace

      - run:
          name: Get birb-cli binary
          command: mv bb-cli-workspace/bb ./
      - run:
          name: Build edgar worker binary
          command: make build-release package=edgar-worker
      - save_cache:
          key: v9-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
            - /root/.cargo


#  build_test_deploy:
#    machine: true
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#            - v8-cargo-cache-{{ arch }}-{{ .Branch }} # Cache for the branch that you're on
#            - v8-cargo-cache-{{ arch }}- # If that doesn't exist, use the default cache across all branches
#      - run:
#          name: Install birb cli
#          command: |
#            source $HOME/.cargo/env
#            cargo install --path crates/birb-cli --force
#      - run:
#          name: Run Tests
#          command: bb test all
#      - run:
#          name: Upgrade AWS CLI Latest Version
#          command: pip install --upgrade awscli
#      - run:
#          name: Build API Binary
#          command: bb build api
#      - run:
#          name: Build Image and Push to ECS
#          command: bb push api
#      - save_cache:
#          key: v9-cargo-cache-{{ arch }}-{{ .Branch }}
#          paths:
#            - target
#            - /usr/local/cargo
#            - /root/.cargo

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install-birb-cli
      - test-edgar:
          requires:
            - install-birb-cli
      - build-edgar:
          requires:
            - install-birb-cli
            - test-edgar
