version: 2.1
jobs:
  test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v8-cargo-cache-{{ arch }}-{{ .Branch }} # Cache for the branch that you're on
            - v8-cargo-cache-{{ arch }}- # If that doesn't exist, use the default cache across all branches
      - run:
          name: Run Tests
          command: make test
  deploy_api:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v8-cargo-cache-{{ arch }}-{{ .Branch }} # Cache for the branch that you're on
            - v8-cargo-cache-{{ arch }}- # If that doesn't exist, use the default cache across all branches
      - run:
          name: Upgrade AWS CLI Latest Version
          command: pip install --upgrade awscli
      - run:
          name: Build API Binary
          command: make build-release package=api
      - run:
          name: Copy Binary and Production Dockerfile to "./out"
          command: make copy-artifact bin=api_bin
      - run:
          name: Build Image and Push to ECS
          command: ./scripts/build_and_push.sh
      - save_cache:
          key: v8-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
            - /root/.cargo
  deploy_lambdas:
    machine: true
      steps:
        - checkout
        - restore_cache:
            keys:
              - v8-cargo-cache-{{ arch }}-{{ .Branch }} # Cache for the branch that you're on
              - v8-cargo-cache-{{ arch }}- # If that doesn't exist, use the default cache across all branches
        - run:
            name: Deploy Edgar Worker
            command: make edgar-worker

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy_api
      - deploy_lambdas
