[package]
name = "filer-status"
version = "0.1.0"
authors = ["Marty Jones <murtin.jones@gmail.com>"]
edition = "2018"

[dependencies]
bson = "0.13.0"
reqwest = "0.9.15"
failure = "0.1.5"

api = { path = "../api", version = "0.1.0" }
