INSERT INTO filing_type
(filing_name, description, is_processable, collectible)
VALUES
    ('10-K', 'Annual report pursuant to section 13 and 15(d)', true, true),
    ('10-Q', 'Quarterly report pursuant to section 13 and 15(d)', true, true),
    ('1-E', 'Notification under Regulation E by small business investment companies and business development companies', false, false),
    ('1-E/A', 'Notification under Regulation E by small business investment companies and business development companies (Amendment)', false, false),
    ('1-E AD', 'Sales material filed pursuant to Rule 607 under Regulation E.', false, false),
    ('1-E AD/A', 'Sales material filed pursuant to Rule 607 under Regulation E. (Amendment)', false, false),
    ('2-E', 'Sales material filed pursuant to Rule 609 under Regulation E.', false, false),
    ('2-E/A', 'Sales material filed pursuant to Rule 609 under Regulation E. (Amendment)', false, false),
    ('10-12B', 'Initial general form for registration of a class of securities pursuant to section 12(b)', false, false),
    ('10-12B/A', 'Initial general form for registration of a class of securities pursuant to section 12(b) (Amendment)', false, false),
    ('10-12G', 'Initial general form for registration of a class of securities pursuant to section 12(g)', false, false),
    ('10-12G/A', 'Initial general form for registration of a class of securities pursuant to section 12(g) (Amendment)', false, false),
    ('10-D', 'Periodic distribution reports by Asset-Backed issuers pursuant to Rule 13a-17 or 15d-17', false, false),
    ('10-D/A', 'Periodic distribution reports by Asset-Backed issuers pursuant to Rule 13a-17 or 15d-17 (Amendment)', false, false),
    ('10-K/A', 'Annual report pursuant to section 13 and 15(d) (Amendment)', false, false),
    ('10-KT', 'Transition report pursuant to Rule 13a-10 or 15d-10', false, false),
    ('10-KT/A', 'Transition report pursuant to Rule 13a-10 or 15d-10 (Amendment)', false, false),
    ('10-Q/A', 'Quarterly report pursuant to section 13 and 15(d) (Amendment)', false, false),
    ('10-QT', 'Transition report pursuant to Rule 13a-10 or 15d-10', false, false),
    ('10-QT/A', 'Transition report pursuant to Rule 13a-10 or 15d-10 (Amendment)', false, false),
    ('11-K', 'Annual report of employee stock purchase, savings and similar plans', false, false),
    ('11-K/A', 'Annual report of employee stock purchase, savings and similar plans (Amendment)', false, false),
    ('11-KT', 'Transition report pursuant to Rule 13a-10 or 15d-10', false, false),
    ('11-KT/A', 'Transition report pursuant to Rule 13a-10 or 15d-10 (Amendment)', false, false),
    ('13F-HR', 'Initial Quarterly Form 13F Holdings report filed by institutional managers', false, false),
    ('13F-HR/A', 'Initial Quarterly Form 13F Holdings report filed by institutional managers (Amendment)', false, false),
    ('13F-NT', 'Initial Quarterly Form 13F Notice Report filed by institutional managers', false, false),
    ('13F-NT/A', 'Initial Quarterly Form 13F Notice Report filed by institutional managers (Amendment)', false, false),
    ('13H', 'Large Trader Registration Information Required of Large Traders Pursuant to the Securities Exchange Act of 1934 and Rule 13h-1 Thereunder. Initial Filing (13H)', false, false),
    ('13H-Q', 'Large Trader Registration Information Required of Large Traders Pursuant to the Securities Exchange Act of 1934 and Rule 13h-1 Thereunder. Amended Filing (13H-Q)', false, false),
    ('13H-A', 'Large Trader Registration Information Required of Large Traders Pursuant to the Securities Exchange Act of 1934 and Rule 13h-1 Thereunder. Annual Filing (13H-A)', false, false),
    ('13H-I', 'Large Trader Registration Information Required of Large Traders Pursuant to the Securities Exchange Act of 1934 and Rule 13h-1 Thereunder. Inactive Status (13H-I)', false, false),
    ('13H-R', 'Large Trader Registration Information Required of Large Traders Pursuant to the Securities Exchange Act of 1934 and Rule 13h-1 Thereunder. Reactivated Status (13H-R)', false, false),
    ('13H-T', 'Large Trader Registration Information Required of Large Traders Pursuant to the Securities Exchange Act of 1934 and Rule 13h-1 Thereunder. Termination Filing (13H-T)', false, false),
    ('144', 'Filing for proposed sale of securities under Rule 144', false, false),
    ('144/A', 'Filing for proposed sale of securities under Rule 144 (Amendment)', false, false),
    ('15-12B', 'Notice of termination of registration of a class of securities under Section 12(b)', false, false),
    ('15-12B/A', 'Notice of termination of registration of a class of securities under Section 12(b) (Amendment)', false, false),
    ('15-12G', 'Notice of termination of registration of a class of securities under Section 12(g)', false, false),
    ('15-12G/A', 'Notice of termination of registration of a class of securities under Section 12(g) (Amendment)', false, false),
    ('15-15D', 'Notice of suspension of duty to file reports pursuant to Section 13 and 15(d) of the Act', false, false),
    ('15-15D/A', 'Notice of suspension of duty to file reports pursuant to Section 13 and 15(d) of the Act (Amendment)', false, false),
    ('15F-12G', 'Notice of termination of a foreign private issuer&#39;s registration of a class of securities under Section 12(g)', false, false),
    ('15F-12G/A', 'Notice of termination of a foreign private issuer&#39;s registration of a class of securities under Section 12(g) (Amendment)', false, false),
    ('15F-15D', 'Notice of a foreign private issuers suspension of duty to file reports pursuant to Section 13 and 15(d) of the Act', false, false),
    ('15F-15D/A', 'Notice of a foreign private issuers suspension of duty to file reports pursuant to Section 13 and 15(d) of the Act (Amendment)', false, false),
    ('18-K', 'Annual report for foreign governments', false, false),
    ('18-K/A', 'Annual report for foreign governments (Amendment)', false, false),
    ('20-F', 'Annual and transition report of foreign private issuers pursuant to sections 13 or 15(d)', false, false),
    ('20-F/A', 'Annual and transition report of foreign private issuers pursuant to sections 13 or 15(d) (Amendment)', false, false),
    ('20FR12B', 'Form for initial registration of a class of securities of foreign private issuers pursuant to section 12(b)', false, false),
    ('20FR12B/A', 'Form for initial registration of a class of securities of foreign private issuers pursuant to section 12(b) (Amendment)', false, false),
    ('20FR12G', 'Form for initial registration of a class of securities of foreign private issuers pursuant to section 12(g)', false, false),
    ('20FR12G/A', 'Form for initial registration of a class of securities of foreign private issuers pursuant to section 12(g) (Amendment)', false, false),
    ('24F-2NT', 'Rule 24F-2 notice filed on Form 24F-2', false, false),
    ('24F-2NT/A', 'Rule 24F-2 notice filed on Form 24F-2 (Amendment)', false, false),
    ('25', 'Notification filed by issuer to voluntarily withdraw a class of securities from listing and registration on a national securities exchange', false, false),
    ('25/A', 'Notification filed by issuer to voluntarily withdraw a class of securities from listing and registration on a national securities exchange (Amendment)', false, false),
    ('25-NSE', 'Notification filed by national security exchange to report the removal from listing and registration of matured, redeemed or retired securities', false, false),
    ('25-NSE/A', 'Notification filed by national security exchange to report the removal from listing and registration of matured, redeemed or retired securities (Amendment)', false, false),
    ('3', 'Initial statement of beneficial ownership of securities', false, false),
    ('3/A', 'Initial statement of beneficial ownership of securities (Amendment)', false, false),
    ('305B2', 'Application for designation of a new trustee under the Trust Indenture Act', false, false),
    ('305B2/A', 'Application for designation of a new trustee under the Trust Indenture Act (Amendment)', false, false),
    ('4', 'Statement of changes in beneficial ownership of securities', false, false),
    ('4/A', 'Statement of changes in beneficial ownership of securities (Amendment)', false, false),
    ('40-6B', 'Application under the Investment Company Act by an employee&#39;s securities company', false, false),
    ('40-6B/A', 'Application under the Investment Company Act by an employee&#39;s securities company (Amendment)', false, false),
    ('40-17F2', 'Initial certificate of accounting of securities and similar investments in the custody of management investment companies', false, false),
    ('40-17F2/A', 'Initial certificate of accounting of securities and similar investments in the custody of management investment companies (Amendment)', false, false),
    ('40-17G', 'Fidelity bond', false, false),
    ('40-17G/A', 'Fidelity bond (Amendment)', false, false),
    ('40-202A/A', 'Filing 40-202A/A', false, false),
    ('40-206A/A', 'Amendment', false, false),
    ('40-24B2', 'Filing of sales literature', false, false),
    ('40-24B2/A', 'Filing of sales literature (Amendment)', false, false),
    ('40-33', 'All stockholder derivative actions filed with a court against an investment company or an affiliate', false, false),
    ('40-8B25', 'Document or Report', false, false),
    ('40-8F-2', 'Initial application for de-registration pursuant to Investment Company Act Rule 0-2', false, false),
    ('40-APP', 'Applications under the Investment Company Act other than those reviewed by Office of Insurance Products', false, false),
    ('40-APP/A', 'Applications under the Investment Company Act other than those reviewed by Office of Insurance Products (Amendment)', false, false),
    ('40-F', 'Annual reports filed by certain Canadian issuers', false, false),
    ('40-F/A', 'Annual reports filed by certain Canadian issuers (Amendment)', false, false),
    ('40-OIP', 'Applications under the Investment Company Act reviewed by Office of Insurance Products', false, false),
    ('40-OIP/A', 'Applications under the Investment Company Act reviewed by Office of Insurance Products (Amendment)', false, false),
    ('40FR12B', 'Registration of a class of securities of certain Canadian issuers', false, false),
    ('40FR12B/A', 'Registration of a class of securities of certain Canadian issuers (Amendment)', false, false),
    ('40FR12G', 'Registration of a class of securities of certain Canadian issuers pursuant to Section 12(g) of the 1934 Act', false, false),
    ('40FR12G/A', 'Registration of a class of securities of certain Canadian issuers pursuant to Section 12(g) of the 1934 Act (Amendment)', false, false),
    ('424A', 'Prospectus', false, false),
    ('424B1', 'Prospectus', false, false),
    ('424B2', 'Prospectus', false, false),
    ('424B3', 'Prospectus', false, false),
    ('424B4', 'Prospectus', false, false),
    ('424B5', 'Prospectus', false, false),
    ('424B7', 'Prospectus', false, false),
    ('424B8', 'Prospectus', false, false),
    ('424H', '', false, false),
    ('425', 'Filing under Securities Act Rule 425 of certain prospectuses and communications in connection with business combination transactions', false, false),
    ('485APOS', 'Post-effective amendment', false, false),
    ('485BPOS', 'Post-effective amendment', false, false),
    ('485BXT', 'Post-effective amendment', false, false),
    ('486APOS', 'Post-effective amendment', false, false),
    ('486BPOS', 'Post-effective amendment', false, false),
    ('487', 'Pre-effective pricing amendment', false, false),
    ('497', 'Definitive materials', false, false),
    ('497AD', 'Filing by certain investment companies of Securities Act Rule 482 advertising in accordance with Securities Act Rule 497', false, false),
    ('497H2', 'Filings made pursuant to Rule 497(h)(2)', false, false),
    ('497J', 'Certification of no change in definitive materials', false, false),
    ('497K', '', false, false),
    ('497K1', 'Profiles for certain open-end management investment companies', false, false),
    ('497K2', 'Profiles for certain open-end management investment companies', false, false),
    ('497K3A', 'Profiles for certain open-end management investment companies', false, false),
    ('497K3B', 'Profiles for certain open-end management investment companies', false, false),
    ('5', 'Insider Trading (Form 5)', false, false),
    ('5/A', 'Insider Trading (Form 5) Amendment', false, false),
    ('6-K', 'Current report of foreign issuer', false, false),
    ('6-K/A', 'Current report of foreign issuer (Amendment)', false, false),
    ('8-A12B', 'Registration of a class of securities on a national securities exchange', false, false),
    ('8-A12B/A', 'Registration of a class of securities on a national securities exchange (Amendment)', false, false),
    ('8-A12G', 'Notification that a class of securities of successor issuer is deemed to be registered', false, false),
    ('8-A12G/A', 'Notification that a class of securities of successor issuer is deemed to be registered (Amendment)', false, false),
    ('8-K', 'Events or Changes Between Quarterly Reports', false, false),
    ('8-K/A', 'Events or Changes Between Quarterly Reports (Amendment)', false, false),
    ('8-K12B', 'Notification that a class of securities of successor issuer is deemed to be registered pursuant to Section 12(b)', false, false),
    ('8-K12B/A', 'Notification that a class of securities of successor issuer is deemed to be registered pursuant to Section 12(b) (Amendment)', false, false),
    ('8-K12G3', 'Notification that a class of securities of successor issuer is deemed to be registered pursuant to Section 12(g)', false, false),
    ('8-K12G3/A', 'Notification that a class of securities of successor issuer is deemed to be registered pursuant to Section 12(g) (Amendment)', false, false),
    ('8-K15D5', 'Notification of assumption of duty to report by successor', false, false),
    ('8-M', '8-M Filing', false, false),
    ('9-M', '9-M Filing', false, false),
    ('ABS-15G', 'ABS-15G Filing', false, false),
    ('ADN-MTL', 'ADN-MTL Filing', false, false),
    ('ADV-E', 'ADV-E Filing', false, false),
    ('ADV-H-C', '', false, false),
    ('ADV-H-T', '', false, false),
    ('ADV-NR', 'ADV-NR Filing', false, false),
    ('ANNLRPT', 'Periodic Development Bank filing, submitted annually', false, false),
    ('APP WD', 'APP WD Filing', false, false),
    ('APP NTC', 'APP NTC Filing', false, false),
    ('APP ORDR', 'APP ORDR Filing', false, false),
    ('ARS', 'Annual Report to Security Holders', false, false),
    ('ARS/A', 'Annual Report to Security Holders (Amendment)', false, false),
    ('AW', 'Withdrawal of amendment to a registration statement filed under the Securities Act', false, false),
    ('AW WD', 'Withdrawal of a request for withdrawal of an amendment to a registration statement', false, false),
    ('CB', 'Certain tender offers, business combinations and rights offerings, in which the subject company is a foreign private issuer of which less than 10% of its securities are held by U.S. persons', false, false),
    ('CB/A', 'Certain tender offers, business combinations and rights offerings, in which the subject company is a foreign private issuer of which less than 10% of its securities are held by U.S. persons (Amendment)', false, false),
    ('CERTAMX', 'Filing CERTAMX', false, false),
    ('CERTNAS', 'Filing CERTNAS', false, false),
    ('CERTNYS', 'Filing CERTNYS', false, false),
    ('CERTPAC', 'Filing CERTPAC', false, false),
    ('CORRESP', 'Correspondence', false, false),
    ('CT ORDER', 'Confidential Treatment Order.', false, false),
    ('D', 'Filing D', false, false),
    ('D/A', 'Filing D (Amendment)', false, false),
    ('DEF 14A', 'Definitive proxy statements', false, false),
    ('DEF 14C', 'Definitive information statements', false, false),
    ('DEFA14A', '', false, false),
    ('DEFA14C', 'Definitive additional information statement materials including Rule 14(a)(12) material', false, false),
    ('DEFC14A', 'Definitive proxy statement in connection with contested solicitations', false, false),
    ('DEFC14C', 'Definitive information statement - contested solicitations', false, false),
    ('DEFM14A', 'Definitive proxy statement relating to merger or acquisition', false, false),
    ('DEFM14C', 'Definitive information statement relating to merger or acquisition', false, false),
    ('DEFN14A', 'Definitive proxy statement filed by non management', false, false),
    ('DEFR14A', 'Definitive revised proxy soliciting materials', false, false),
    ('DEFR14C', 'Definitive revised information statement materials', false, false),
    ('DEL AM', 'Separately filed delaying amendment', false, false),
    ('DFAN14A', 'Definitive additional proxy soliciting materials filed by non-management', false, false),
    ('DFRN14A', 'Revised definitive proxy statement filed by non-management', false, false),
    ('DSTRBRPT', 'Distribution of primary obligations Development Bank report', false, false),
    ('EFFECT', 'Filing EFFECT', false, false),
    ('F-1', 'Registration statement for securities of certain foreign private issuers', false, false),
    ('F-1/A', 'Registration statement for securities of certain foreign private issuers (Amendment)', false, false),
    ('F-10', 'Registration statement for securities of certain Canadian issuers', false, false),
    ('F-10/A', 'Registration statement for securities of certain Canadian issuers (Amendment)', false, false),
    ('F-10EF', 'Auto effective registration statement for securities of certain Canadian issuer under the Securities Act of 1933', false, false),
    ('F-10POS', 'Post-effective amendment to a F-10EF registration', false, false),
    ('F-1MEF', 'A new registration statement filed under Rule 462(b) to add securities to a prior related effective registration statement filed on Form F-1', false, false),
    ('F-3', 'Registration statement for specified transactions by certain foreign private issuers', false, false),
    ('F-3/A', 'Registration statement for specified transactions by certain foreign private issuers (Amendment)', false, false),
    ('F-3ASR', 'Automatic shelf registration statement of securities of well-known seasoned issuers', false, false),
    ('F-3D', 'Registration statement for dividend or interest reinvestment plan securities of foreign private issuers', false, false),
    ('F-3DPOS', 'Post-Effective amendment to a F-3D registration', false, false),
    ('F-4', 'Registration statement for securities issued by foreign private issuers in certain business combination transactions', false, false),
    ('F-4 POS', 'Post-effective amendment to a F-4EF registration', false, false),
    ('F-4/A', 'Registration statement for securities issued by foreign private issuers in certain business combination transactions (Amendment)', false, false),
    ('F-6', 'Registration statement for American Depositary Receipts representing securities of certain foreign private issuers', false, false),
    ('F-6 POS', 'Post-effective amendment to a F-6EF registration', false, false),
    ('F-6/A', 'Registration statement for American Depositary Receipts representing securities of certain foreign private issuers (Amendment)', false, false),
    ('F-6EF', 'Auto effective registration statement for American Depositary Receipts representing securities of certain foreign private issuers', false, false),
    ('F-7', 'Registration statement for securities of certain Canadian issuers offered for cash upon the exercise of rights granted to existing security holders', false, false),
    ('F-7 POS', 'Post-effective amendment to a F-7 registration', false, false),
    ('F-7/A', 'Amendment', false, false),
    ('F-8', 'Registration statement for securities of certain Canadian issuers to be issued in exchange offers or a business combination', false, false),
    ('F-8/A', 'Registration statement for securities of certain Canadian issuers to be issued in exchange offers or a business combination (Amendment)', false, false),
    ('F-80', 'Registration of securities of certain Canadian issuers to be issued in exchange offers or a business combination under the Securities Act of 1933', false, false),
    ('F-9', 'Registration of securities of certain investment grade debt or investment grade preferred securities of certain Canadian issuers', false, false),
    ('F-9/A', 'Registration of securities of certain investment grade debt or investment grade preferred securities of certain Canadian issuers (Amendment)', false, false),
    ('F-N', 'Notification of the appointment of an agent for service by certain foreign institutions', false, false),
    ('F-X', 'For appointment of agent for service of process by issuers registering securities', false, false),
    ('F-X/A', 'For appointment of agent for service of process by issuers registering securities (Amendment)', false, false),
    ('FOCUSN', 'FOCUSN Filing', false, false),
    ('FOCUSN/A', 'FOCUSN Filing (Amendment)', false, false),
    ('FWP', 'Filing under Securities Act Rules 163/433 of free writing prospectuses', false, false),
    ('G-405', 'G-405 Filing', false, false),
    ('G-405N', '', false, false),
    ('G-FIN', 'G-FIN Filing', false, false),
    ('G-FIN/A', 'G-FIN/A Filing (Amendment)', false, false),
    ('MSD', '', false, false),
    ('MSD/A', 'MSD/A Filing (Amendment)', false, false),
    ('MSDW', 'MSDW Filing', false, false),
    ('N-14', 'Initial registration statement for open-end investment company', false, false),
    ('N-14 8C', 'Initial registration statement filed on Form N14 by closed-end investment company (business combinations)', false, false),
    ('N-14 8C/A', 'Initial registration statement filed on Form N14 by closed-end investment company (business combinations) Amendment', false, false),
    ('N-14/A', 'Initial registration statement for open-end investment company (Amendment)', false, false),
    ('N-14AE', 'Filing N-14AE', false, false),
    ('N-14AE/A', 'N-14AE (Amendment)', false, false),
    ('N-18F1', 'Initial notification of election pursuant to Rule 18f-1 filed on Form N-18F-1', false, false),
    ('N-18F1/A', 'Initial notification of election pursuant to Rule 18f-1 filed on Form N-18F-1 (Amendment)', false, false),
    ('N-1A', 'Initial registration statement for open-end management investment companies', false, false),
    ('N-1A/A', 'Initial registration statement for open-end management investment companies', false, false),
    ('N-2', 'Initial filing of a registration statement on Form N-2 for closed-end investment companies', false, false),
    ('N-2/A', 'Initial filing of a registration statement on Form N-2 for closed-end investment companies (Amendment)', false, false),
    ('N-23C-2', 'Notice by closed-end investment companies of intention to call or redeem their own securities', false, false),
    ('N-23C-2/A', 'Notice by closed-end investment companies of intention to call or redeem their own securities (Amendment)', false, false),
    ('N-23C3A', 'Notification of periodic repurchase offer Filed pursuant to Rule 23c-3(b) only', false, false),
    ('N-23C3A/A', 'Notification of periodic repurchase offer Filed pursuant to Rule 23c-3(b) only (Amendment)', false, false),
    ('N-23C3B', 'Filing N-23C3B', false, false),
    ('N-23C3C', '', false, false),
    ('N-23C3C/A', 'Filing N-23C3C/A', false, false),
    ('N-2MEF', '', false, false),
    ('N-3', 'Initial registration statement on Form N-3 for separate accounts (management investment companies)', false, false),
    ('N-30B-2', 'Periodic and interim reports mailed to investment company shareholders', false, false),
    ('N-30D', 'Initial annual and semi-annual reports mailed to investment company shareholders', false, false),
    ('N-30D/A', 'Amendment', false, false),
    ('N-4', 'Initial registration statement on Form N-4 for separate accounts (unit investment trusts)', false, false),
    ('N-4/A', 'Initial registration statement on Form N-4 for separate accounts (unit investment trusts) Amendment', false, false),
    ('N-54A', 'Notification of election by business development companies', false, false),
    ('N-54C', 'Notification of election by business development companies', false, false),
    ('N-54C/A', 'Notification of election by business development companies (Amendment)', false, false),
    ('N-6', 'Registration statement for separate accounts', false, false),
    ('N-6/A', 'Registration statement for separate accounts (Amendment)', false, false),
    ('N-6F', 'Notice of intent by business development companies to elect to be subject to Sections 55 through 65 of the 1940 Act filed on Form N-6F', false, false),
    ('N-8A', 'Initial notification of registration under section 8(a) filed on Form N-8A', false, false),
    ('N-8A/A', 'Initial notification of registration under section 8(a) filed on Form N-8A (Amendment)', false, false),
    ('N-8B-2', 'Initial registration statement for unit investment trusts', false, false),
    ('N-8B-2/A', 'Initial registration statement for unit investment trusts', false, false),
    ('N-8F', 'Application for deregistration made on Form N-8F', false, false),
    ('N-8F/A', 'Application for deregistration made on Form N-8F (Amendment)', false, false),
    ('N-CSR', 'Certified annual shareholder report of registered management investment companies', false, false),
    ('N-CSR/A', 'Certified annual shareholder report of registered management investment companies (Amendment)', false, false),
    ('N-CSRS', 'Certified semi-annual shareholder report of registered management investment companies', false, false),
    ('N-CSRS/A', 'Certified semi-annual shareholder report of registered management investment companies (Amendment)', false, false),
    ('N-MFP', 'Monthly Schedule Of Portfolio Holdings Of Money Market Funds', false, false),
    ('N-PX', 'Annual Report of Proxy Voting Record of Registered Management Investment Companies', false, false),
    ('N-PX/A', 'Annual Report of Proxy Voting Record of Registered Management Investment Companies', false, false),
    ('N-Q', 'Quarterly Schedule of Portfolio Holdings of Registered Management Investment Company', false, false),
    ('N-Q/A', 'Quarterly Schedule of Portfolio Holdings of Registered Management Investment Company', false, false),
    ('NO ACT', 'NO ACT Filing', false, false),
    ('NSAR-A', 'Semi-annual report for management companies', false, false),
    ('NSAR-A/A', 'Semi-annual report for management companies (Amendment)', false, false),
    ('NSAR-AT', '', false, false),
    ('NSAR-B', 'Annual report for management companies', false, false),
    ('NSAR-B/A', 'Annual report for management companies (Amendment)', false, false),
    ('NSAR-BT', 'Transitional annual report filed on Form NSAR', false, false),
    ('NSAR-BT/A', 'Transitional annual report filed on Form NSAR (Amendment)', false, false),
    ('NSAR-U', 'Annual report for unit investment trusts', false, false),
    ('NSAR-U/A', 'Annual report for unit investment trusts (Amendment)', false, false),
    ('NT 10-K', 'Notice under Rule 12b25 of inability to timely file all or part of a Form 10-K, 10-KSB, or 10KT', false, false),
    ('NT 10-K/A', 'Notice under Rule 12b25 of inability to timely file all or part of a Form 10-K, 10-KSB, or 10KT (Amendment)', false, false),
    ('NT 10-Q', 'Notice under Rule 12b25 of inability to timely file all or part of a form 10-Q or 10-QSB', false, false),
    ('NT 10-Q/A', 'Notice under Rule 12b25 of inability to timely file all or part of a form 10-Q or 10-QSB (Amendment)', false, false),
    ('NT 11-K', 'Notice under Rule 12b25 of inability to timely file all or part of a form 11-K', false, false),
    ('NT 15D2', '', false, false),
    ('NT 20-F', 'Notice under Rule 12b25 of inability to timely file all or part of an annual report of form 20-F', false, false),
    ('NT 20-F/A', 'Notice under Rule 12b25 of inability to timely file all or part of an annual report of form 20-F (Amendment)', false, false),
    ('NT-NCSR', 'Notice under Exchange Act Rule 12b-25 of inability to timely file Form N-CSR (annual or semi-annual report)', false, false),
    ('NT-NCSR/A', 'Notice under Exchange Act Rule 12b-25 of inability to timely file Form N-CSR (annual or semi-annual report) Amendment', false, false),
    ('NT-NSAR', 'Notice under Exchange Act Rule 12b-25 of inability to timely file Form N-SAR', false, false),
    ('NT-NSAR/A', 'Notice under Exchange Act Rule 12b-25 of inability to timely file Form N-SAR (Amendment)', false, false),
    ('NTFNCSR', '', false, false),
    ('NTFNSAR', '', false, false),
    ('NTN 10K', 'Filing NTN 10K', false, false),
    ('NTN 10Q', 'Filing NTN 10Q', false, false),
    ('NTN 20F', 'Filing NTN 20F', false, false),
    ('POS 8C', 'Post-effective amendment by closed-end investment companies', false, false),
    ('POS AM', 'Post-effective amendment to a registration statement that is not immediately effective upon filing', false, false),
    ('POS AMI', 'Post-effective amendment', false, false),
    ('POS EX', 'Post-effective amendment filed solely to add exhibits to a registration statement', false, false),
    ('POS462B', 'Post-effective amendment to Securities Act Rule 462(b) registration statement', false, false),
    ('POS462C', 'Post-effective amendment to a registration statement filed under Rule 462(c)', false, false),
    ('POSASR', 'Post-effective amendment to an automatic shelf registration statement on Form S-3ASR or Form F-3ASR', false, false),
    ('PRE 14A', 'Preliminary proxy statement not related to a contested matter or merger/acquisition', false, false),
    ('PRE 14C', 'Preliminary information statement not related to a contested matter or merger/acquisition', false, false),
    ('PREC14A', 'Preliminary proxy statement in connection with contested solicitations', false, false),
    ('PREC14C', 'Preliminary information statements - contested solicitations', false, false),
    ('PREM14A', 'Preliminary proxy statements relating to merger or acquisition', false, false),
    ('PREM14C', 'Preliminary information statements relating to merger or acquisition', false, false),
    ('PREN14A', 'Preliminary proxy statement filed by non-management', false, false),
    ('PRER14A', 'Preliminary revised proxy soliciting materials', false, false),
    ('PRER14C', 'Preliminary revised information statements', false, false),
    ('PRRN14A', 'Revised preliminary proxy statement filed by non-management', false, false),
    ('PX14A6G', 'Notice of exempt solicitation', false, false),
    ('PX14A6N', '', false, false),
    ('QRTLYRPT', 'Periodic Development Bank filing, submitted quarterly', false, false),
    ('REG-NR', 'REG-NR Filing', false, false),
    ('REGDEX', 'Regulation D Exemption Filing', false, false),
    ('REGDEX/A', 'REGDEX Filing (Amendment)', false, false),
    ('REVOKED', '', false, false),
    ('RW', 'Registration Withdrawal Request', false, false),
    ('RW WD', 'Withdrawal of a Registration Withdrawal Request', false, false),
    ('S-1', 'IPO Registration', false, false),
    ('S-1/A', 'IPO Registration (Amendment)', false, false),
    ('S-11', 'Registration statement for securities to be issued by real estate companies', false, false),
    ('S-11/A', 'Registration statement for securities to be issued by real estate companies (Amendment)', false, false),
    ('S-11MEF', 'A new registration statement filed under Rule 462(b) to add securities to a prior related effective registration statement filed on Form S 11', false, false),
    ('S-1MEF', 'A new registration statement filed under Rule 462(b) to add securities to a prior related effective registration statement filed on Form S 1', false, false),
    ('S-3', 'Registration statement for specified transactions by certain issuers', false, false),
    ('S-3/A', 'Registration statement for specified transactions by certain issuers (Amendment)', false, false),
    ('S-3ASR', 'Automatic shelf registration statement of securities of well-known seasoned issuers', false, false),
    ('S-3D', 'Automatically effective registration statement for securities issued pursuant to dividend or interest reinvestment plans', false, false),
    ('S-3DPOS', 'Post-effective amendment to a S-3D registration statement', false, false),
    ('S-3MEF', 'A new registration statement filed under Rule 462(b) to add securities to a prior related effective registration statement filed on Form S 3', false, false),
    ('S-4', 'Registration of securities issued in business combination transactions', false, false),
    ('S-4 POS', 'Post-effective amendment to a S-4EF registration statement', false, false),
    ('S-4/A', 'Registration of securities issued in business combination transactions (Amendment)', false, false),
    ('S-4EF', '', false, false),
    ('S-4EF/A', '', false, false),
    ('S-4MEF', 'A new registration statement filed under Rule 462(b) to add securities to a prior related effective registration statement filed on Form S-4', false, false),
    ('S-6', 'Initial registration statement filed on Form S-6 for unit investment trusts', false, false),
    ('S-6/A', 'Initial registration statement filed on Form S-6 for unit investment trusts (Amendment)', false, false),
    ('S-8', 'Initial registration statement for securities to be offered to employees pursuant to employee benefit plans', false, false),
    ('S-8 POS', 'Post-effective amendment to a S-8 registration statement', false, false),
    ('S-B', 'Registration statement for securities of foreign governments and subdivisions', false, false),
    ('S-B/A', 'Registration statement for securities of foreign governments and subdivisions (Amendment)', false, false),
    ('S-BMEF', 'A new registration statement filed under Rule 462(b) to add securities to a prior related effective registration statement filed on Form SB-1', false, false),
    ('SB-1', '', false, false),
    ('SB-1/A', '', false, false),
    ('SB-2', '', false, false),
    ('SB-2/A', '', false, false),
    ('SB-2MEF', '', false, false),
    ('SC 13D', 'Schedule filed to report acquisition of beneficial ownership of more than 5% of a class of equity securities', false, false),
    ('SC 13D/A', 'Schedule filed to report acquisition of beneficial ownership of more than 5% of a class of equity securities (Amendment)', false, false),
    ('SC 13E3', 'Schedule filed to report going private transactions', false, false),
    ('SC 13E3/A', 'Schedule filed to report going private transactions (Amendment)', false, false),
    ('SC 13G', 'Schedule filed to report acquisition of beneficial ownership of more than 5% of a class of equity securities by passive investors and certain institutions', false, false),
    ('SC 13G/A', 'Schedule filed to report acquisition of beneficial ownership of more than 5% of a class of equity securities by passive investors and certain institutions (Amendment)', false, false),
    ('SC 14D9', 'Tender offer solicitation/recommendation statements filed under Rule 14d-9', false, false),
    ('SC 14D9/A', 'Tender offer solicitation/recommendation statements filed under Rule 14d-9 (Amendment)', false, false),
    ('SC 14F1', 'Statement regarding change in majority of directors pursuant to Rule 14f-1', false, false),
    ('SC 14F1/A', 'Statement regarding change in majority of directors pursuant to Rule 14f-1 (Amendment)', false, false),
    ('SC TO-C', 'Written communication relating to an issuer or third party tender offer', false, false),
    ('SC TO-I', 'Issuer tender offer statement', false, false),
    ('SC TO-I/A', 'Issuer tender offer statement (Amendment)', false, false),
    ('SC TO-T', 'Third party tender offer statement', false, false),
    ('SC TO-T/A', 'Third party tender offer statement (Amendment)', false, false),
    ('SC13E4F', 'Issuer tender offer statement filed pursuant to Rule 13(e)(4) by foreign issuers', false, false),
    ('SC13E4F/A', 'Issuer tender offer statement filed pursuant to Rule 13(e)(4) by foreign issuers (Amendment)', false, false),
    ('SC14D1F', 'Third party tender offer statement filed pursuant to Rule 14d-1(b) by foreign issuers', false, false),
    ('SC14D1F/A', 'Third party tender offer statement filed pursuant to Rule 14d-1(b) by foreign issuers (Amendment)', false, false),
    ('SC14D9C', 'Written communication by the subject company relating to a third party tender offer', false, false),
    ('SC14D9F', '', false, false),
    ('SC14D9F/A', '', false, false),
    ('SE', 'SE Filing', false, false),
    ('SP 15D2', '', false, false),
    ('SUPPL', 'Voluntary supplemental material filed pursuant to Section 11(a) of the Securities Act of 1933 by foreign issuers', false, false),
    ('T-3', 'Initial application for qualification of trust indentures', false, false),
    ('T-3/A', 'Initial application for qualification of trust indentures (Amendment)', false, false),
    ('TA-1', 'Application for registration as a transfer agent filed pursuant to the Securities Exchange Act of 1934', false, false),
    ('TA-1/A', 'Application for registration as a transfer agent filed pursuant to the Securities Exchange Act of 1934 (Amendment)', false, false),
    ('TA-2', 'Annual report of transfer agent activities filed pursuant to the Securities Exchange Act of 1934', false, false),
    ('TA-2/A', 'Annual report of transfer agent activities filed pursuant to the Securities Exchange Act of 1934 (Amendment)', false, false),
    ('TA-W', 'Notice of withdrawal from registration as transfer agent filed pursuant to the Securities Exchange Act of 1934', false, false),
    ('TTW', 'TTW Filing', false, false),
    ('UNDER', '', false, false),
    ('UPLOAD', 'UPLOAD Filing', false, false),
    ('WDL-REQ', 'WDL-REQ Filing', false, false),
    ('X-17A-5', 'X-17A-5 Filing', false, false),
    ('X-17A-5/A', 'X-17A-5/A Filing (Amendment)', false, false),
    ('MA-I/A', NULL, false, false),
    ('MA-I', NULL, false, false),
    ('MA-W', NULL, false, false),
    ('15F-12B', NULL, false, false),
    ('IRANNOTICE', NULL, false, false),
    ('F-N/A', NULL, false, false),
    ('ABS-15G/A', NULL, false, false),
    ('8F-2 NTC', NULL, false, false),
    ('8F-2 ORDR', NULL, false, false),
    ('G-FINW', NULL, false, false),
    ('N-MFP/A', NULL, false, false),
    ('MA-A', NULL, false, false),
    ('MA/A', NULL, false, false),
    ('CERTARCA', NULL, false, false),
    ('N-8F NTC', NULL, false, false),
    ('NRSRO-CE', NULL, false, false),
    ('NT N-MFP', NULL, false, false),
    ('APP WDG', NULL, false, false),
    ('1-A POS', NULL, false, false),
    ('1-A/A', NULL, false, false),
    ('1-A', NULL, false, false),
    ('SD', NULL, false, false),
    ('SF-3/A', NULL, false, false),
    ('QUALIF', NULL, false, false),
    ('DRS/A', NULL, false, false),
    ('N-8F ORDR', NULL, false, false),
    ('1/A', NULL, false, false),
    ('19B-4E', NULL, false, false),
    ('SF-3', NULL, false, false),
    ('CERTBATS', NULL, false, false),
    ('6B NTC', NULL, false, false),
    ('N-CR', NULL, false, false),
    ('40-17F1', NULL, false, false),
    ('DRS', NULL, false, false),
    ('DRSLTR', NULL, false, false),
    ('253G2', NULL, false, false),
    ('MA', NULL, false, false),
    ('1-Z', NULL, false, false),
    ('40-17GCS', NULL, false, false),
    ('1-U', NULL, false, false),
    ('1-A-W', NULL, false, false),
    ('424H/A', NULL, false, false),
    ('1-Z/A', NULL, false, false),
    ('DOS', NULL, false, false),
    ('CFPORTAL', NULL, false, false),
    ('253G1', NULL, false, false),
    ('NRSRO-UPD', NULL, false, false),
    ('DOS/A', NULL, false, false),
    ('DOSLTR', NULL, false, false),
    ('N-6F/A', NULL, false, false),
    ('CFPORTAL/A', NULL, false, false),
    ('SC 13E1/A', NULL, false, false),
    ('F-80POS', NULL, false, false),
    ('SF-1/A', NULL, false, false),
    ('SF-1', NULL, false, false),
    ('N-MFP1', NULL, false, false),
    ('N-MFP1/A', NULL, false, false),
    ('NT N-MFP1', NULL, false, false),
    ('13FCONP', NULL, false, false),
    ('6B ORDR', NULL, false, false),
    ('CERT', NULL, false, false),
    ('40-17F1/A', NULL, false, false),
    ('N-CR/A', NULL, false, false),
    ('1-K', NULL, false, false),
    ('STOP ORDER', NULL, false, false),
    ('1-SA', NULL, false, false),
    ('C/A', NULL, false, false),
    ('C', NULL, false, false),
    ('NRSRO-CE/A', NULL, false, false),
    ('F-4MEF', NULL, false, false),
    ('SDR', NULL, false, false),
    ('C-W', NULL, false, false),
    ('1-A-W/A', NULL, false, false),
    ('SD/A', NULL, false, false),
    ('40-206A', NULL, false, false),
    ('F-3MEF', NULL, false, false),
    ('1-SA/A', NULL, false, false),
    ('1-K/A', NULL, false, false),
    ('1-U/A', NULL, false, false),
    ('C-U', NULL, false, false),
    ('1', NULL, false, false),
    ('40-202A', NULL, false, false),
    ('OIP NTC', NULL, false, false),
    ('OIP ORDR', NULL, false, false),
    ('N-MFP2/A', NULL, false, false),
    ('N-MFP2', NULL, false, false),
    ('ABS-EE', NULL, false, false),
    ('ABS-EE/A', NULL, false, false),
    ('NT N-MFP2', NULL, false, false),
    ('SC 14N/A', NULL, false, false),
    ('SC 14N', NULL, false, false),
    ('253G3', NULL, false, false),
    ('CFPORTAL-W', NULL, false, false),
    ('C/A-W', NULL, false, false),
    ('40-33/A', NULL, false, false),
    ('TH', NULL, false, false),
    ('F-8 POS', NULL, false, false),
    ('253G4', NULL, false, false),
    ('C-AR', NULL, false, false),
    ('NT 10-D', NULL, false, false),
    ('C-TR', NULL, false, false),
    ('1-Z-W', NULL, false, false),
    ('SDR/A', NULL, false, false),
    ('C-AR/A', NULL, false, false),
    ('34-12H', NULL, false, false),
    ('DSTRBRPT/A', NULL, false, false),
    ('APP WD/A', NULL, false, false),
    ('15F-12B/A', NULL, false, false),
    ('C-U-W', NULL, false, false),
    ('CERTCBO', NULL, false, false),
    ('F-80/A', NULL, false, false),
    ('NTFNCEN', NULL, false, false),
    ('SEC ACTION', NULL, false, false),
    ('NPORT-EX', NULL, false, false),
    ('NPORT-EX/A', NULL, false, false),
    ('NT NPORT-EX', NULL, false, false),
    ('NPORT-P', NULL, false, false),
    ('NPORT-P/A', NULL, false, false),
    ('ATS-N', NULL, false, false),
    ('ATS-N/MA', NULL, false, false),
    ('ATS-N/UA', NULL, false, false),
    ('ATS-N/CA', NULL, false, false),
    ('ATS-N/OFA', NULL, false, false),
    ('ATS-N-C', NULL, false, false),
    ('ATS-N-W', NULL, false, false)
ON CONFLICT DO NOTHING;



