[package]
name = "filing-metadata"
version = "0.1.0"
authors = ["Marty Jones <murtin.jones@gmail.com>"]
edition = "2018"

[dependencies]
rusoto_core = "0.38.0"
rusoto_s3 = "0.38.0"
futures = "0.1.27"
