[package]
name = "filing-parser"
version = "0.1.0"
authors = ["Marty Jones <murtin.jones@gmail.com>"]
edition = "2018"

[dependencies]
html5ever = "*"
xml5ever = "*"
markup5ever = "*"
failure = "*"
tendril = "*"
regex = "*"
lazy_static = "*"
mac = "*"
rand = "*"
aws = { path = "../aws", version = "*" }
