[package]
name = "filing-parser"
version = "0.1.0"
authors = ["Marty Jones <murtin.jones@gmail.com>"]
edition = "2018"

[dependencies]
html5ever = "^0.23.0"
xml5ever = "^0.14.0"
markup5ever = "^0.8.1"
failure = "*"
tendril = "*"
regex = "*"
lazy_static = "*"
mac = "*"
rand = "*"
rayon = "*"
rusoto_s3 = "*"
aws = { path = "../aws", version = "*" }
