[package]
name = "utils"
version = "0.1.0"
authors = ["Marty Jones <murtin.jones@gmail.com>"]
edition = "2018"

[dependencies]
flate2 = "^1.0.11"
postgres = { version = "0.15", features = ["with-chrono"] }
