[package]
name = "edgar-worker"
version = "0.1.0"
authors = ["Marty Jones <murtin.jones@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
serde = "1.0.90"
serde_json = "1.0"
serde_derive = "1.0.90"
postgres = "0.15.2"
dotenv = "0.13.0"
cfg-if = "0.1.7"

[dependencies.rocket_contrib]
version = "0.4.0"
features = ["postgres_pool"]

[[bin]]
name = "edgar_worker"
path = "src/bin.rs"
