[package]
name = "edgar-worker"
version = "0.1.0"
authors = ["Marty Jones <murtin.jones@gmail.com>"]
edition = "2018"
autobins = false

[dependencies]
rocket = "0.4.0"
serde = "1.0.90"
serde_json = "1.0"
serde_derive = "1.0.90"
postgres = "0.15.2"
dotenv = "0.13.0"
cfg-if = "0.1.7"
simple_logger = "1.0.1"
log = "0.4.6"
more-asserts = "0.2.1"

api = { path = "../api", version = "0.1.0" }
filer-status = { path = "../filer-status", version = "0.1.0" }

[dependencies.rocket_contrib]
version = "0.4.0"
features = ["postgres_pool"]

[[bin]]
name="edgar-worker"
path="src/main.rs"
