FROM alpine:latest

# This is run from the project-root/out which has the binary in it as well
COPY ./edgar-worker /edgar-worker

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
ENV SSL_CERT_DIR=/etc/ssl/certs

ENTRYPOINT ["/edgar-worker"]
