FROM scratch

# This is run from the project-root/out which has the binary in it as well
COPY ./api_bin /api_bin

ENV ROCKET_ENV=production
ENV ROCKET_PORT=10050

EXPOSE 10050/tcp

ENTRYPOINT ["/api_bin"]
